Edu 4 organisation crud endpoints
VerglasSoftware/educatr-monorepo pull request #15
Opened 2024-11-20 21:10 UTC by JakeyGilly

is this done???

2024-11-20 22:05 UTC, dandabs requested changes

2024-11-20 22:05 UTC, dandabs commented on packages/functions/src/organisation.ts
> +			ownerId: event.requestContext.authorizer?.iam.cognitoIdentity.identityId,
org shouldnt have an owner

2024-11-20 22:05 UTC, dandabs commented on packages/functions/src/organisation.ts
> +		throw new Error("Missing id in path parameters");
see ma's comment about capitalisation

2024-11-20 22:14 UTC, dandabs approved these changes

2024-11-21 00:41 UTC, JustMentalMatt reviewed
packages/functions/src/organisation.ts

caps TK just to keep it consistent. line 85 and 122

2024-11-21 20:55 UTC, merged