EDU-41 favicon
VerglasSoftware/educatr-monorepo pull request #28
Opened 2024-11-27 12:39 UTC by DylanMcKenzie

2024-11-27 15:10 UTC, dandabs requested changes
prettify tsx doesn't seem to be working in the action

2024-11-27 15:23 UTC, JakeyGilly commented
> 41

i dont think its working in anything because frontend doesnt look prettified

2024-11-27 15:25 UTC, dandabs commented
> > prettify tsx doesn't seem to be working in the action
> 
> 
> 
> i dont think its working in anything because frontend doesnt look prettified

yeah? this ticket is meant to fix it - look at the code

2024-11-27 15:25 UTC, JakeyGilly commented
> > > prettify tsx doesn't seem to be working in the action
> > 
> > 
> > i dont think its working in anything because frontend doesnt look prettified
> 
> yeah? this ticket is meant to fix it - look at the code

oh

2024-11-27 15:27 UTC, dandabs requested changes

2024-11-27 15:27 UTC, dandabs commented on packages/frontend/public/resources/images/favicon/site.webmanifest
> +  "name": "MyWebSite",
mywebsite?

2024-12-07 18:36 UTC, dandabs commented
@DylanMcKenzie eta on this ticket?

2024-12-12 10:10 UTC, merged